KEY_WORD = 'Калькулятор'


EXPRESSION1 = '(1 + 2) x 3 - 40 / 5'
CORRECTEXPRESSION1 = "(1 + 2) × 3 - 40 ÷ 5 ="
EXPRESSION2 = '6 / 0'
CORRECTEXPRESSION2 = '6 ÷ 0 ='
EXPRESSION3 = 'sin'
CORRECTEXPRESSION3 = 'sin() ='
EXPRESSIONSLIST = [EXPRESSION1, EXPRESSION2, EXPRESSION3]
CORRECTEXPRESSIONSLIST = [CORRECTEXPRESSION1, CORRECTEXPRESSION2, CORRECTEXPRESSION3]


ANSWER1 = '1'
ANSWER2 = 'Infinity'
ANSWER3 = 'Error'
ANSWERSLIST = [ANSWER1, ANSWER2, ANSWER3]


LANDING_PAGE_URL = 'http://google.com/'
